cc_test(
    name = "ComponentFunctionTest",
    srcs = [
        "ComponentFunctionTest.cpp"
    ],
    deps = [
        "@gtest//:gtest",
        "//lib:PumpkinSpice",
    ],
    data = [
        "FunctionTest.pumpkin",
        "empty.spice"
    ]
)