cc_test(
    name = "InputComponentTest",
    srcs = [
        "InputComponentTest.cpp"
    ],
    deps = [
        "@gtest//:gtest",
        "//lib:PumpkinSpice",
    ],
    data = [
        "InputComponentTest.pumpkin",
        "empty.spice"
    ]
)