cc_library(
    name = "basicComponent",
    hdrs = [
        "BasicComponent.h"
    ],
    deps = [
        "//lib:PumpkinSpice",
    ],
    data = [
        "basic.spice",
        "basic.pumpkin",
    ],
    visibility = ["//examples/basicComponent:__subpackages__"]
)